theme: jekyll-theme-cayman
title: Mutex Monk
author:
  name:  Srinivas
  url:   https://github.com/Vi-Sri
  email: srinivasvishal7@gmail.com
description: A personal blog about exploring the sciences of perception and cognition modeled into computers.
github:
  is_project_page: False
collections:
  tags:
    output: true
    permalink: tag/:path/
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme